{% set name = "doubleml" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/D/DoubleML/DoubleML-{{ version }}.tar.gz
  sha256: a7cc0616de1270642c38047b1a3e4657da8b26dadbe49c74543b4d7fb0be4b73

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - joblib
    - numpy
    - pandas
    - scipy
    - scikit-learn >=1.4.0,<1.6.0
    - statsmodels
    - plotly
    - matplotlib-base

test:
  requires:
    - pytest
    - xgboost
    - python {{ python_min }}
  commands:
    - pytest --pyargs doubleml -m ci
  imports:
    - doubleml

about:
  home: https://docs.doubleml.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Double Machine Learning in Python
  description: |
    The Python package DoubleML provides an implementation of the double / debiased machine learning framework of
    Chernozhukov et al. (2018). It is built on top of scikit-learn (Pedregosa et al., 2011).
  doc_url: https://docs.doubleml.org/stable/
  dev_url: https://github.com/DoubleML/doubleml-for-py

extra:
  recipe-maintainers:
    - SvenKlaassen
    - PhilippBach
    - MalteKurz
