{% set name = "doubleml" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/D/DoubleML/{{ name }}-{{ version }}.tar.gz
  sha256: 54d02439bfcc97704463a9727420a4cb6ebb559a870c645bbc6b21d30f09c972

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - joblib
    - numpy
    - pandas
    - scipy
    - scikit-learn >=1.4.0
    - statsmodels
    - matplotlib-base
    - seaborn >=0.13
    - plotly

test:
  requires:
    - pytest
    - xgboost
    - lightgbm
    - python {{ python_min }}
  commands:
    - pytest --pyargs doubleml -m ci
  imports:
    - doubleml

about:
  home: https://docs.doubleml.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Double Machine Learning in Python
  description: |
    The Python package DoubleML provides an implementation of the double / debiased machine learning framework of
    Chernozhukov et al. (2018). It is built on top of scikit-learn (Pedregosa et al., 2011).
  doc_url: https://docs.doubleml.org/stable/
  dev_url: https://github.com/DoubleML/doubleml-for-py

extra:
  recipe-maintainers:
    - SvenKlaassen
    - PhilippBach
    - MalteKurz
