{% set name = "doubleml" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/D/DoubleML/DoubleML-{{ version }}.tar.gz
  sha256: 6eb63a07f6ee5069da12d439cf3be7c344a0b29e5d4b3d5cf97747a16b200998

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - joblib
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - statsmodels

test:
  requires:
    - pytest
    - xgboost
  commands:
    - pytest --pyargs doubleml -m ci
  imports:
    - doubleml

about:
  home: https://docs.doubleml.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Double Machine Learning in Python
  description: |
    The Python package DoubleML provides an implementation of the double / debiased machine learning framework of
    Chernozhukov et al. (2018). It is built on top of scikit-learn (Pedregosa et al., 2011).
  doc_url: https://docs.doubleml.org/stable/
  dev_url: https://github.com/DoubleML/doubleml-for-py

extra:
  recipe-maintainers:
    - SvenKlaassen
    - PhilippBach
    - MalteKurz
