{% set name = "doubleml" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/D/DoubleML/DoubleML-{{ version }}.tar.gz
  sha256: d80585c8db89c3991694df0c30173c863f92a1e8e954210c00586d7ec0f99fcf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - joblib
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - statsmodels
    - plotly
    - matplotlib-base

test:
  requires:
    - pytest
    - xgboost
  commands:
    - pytest --pyargs doubleml -m ci
  imports:
    - doubleml

about:
  home: https://docs.doubleml.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Double Machine Learning in Python
  description: |
    The Python package DoubleML provides an implementation of the double / debiased machine learning framework of
    Chernozhukov et al. (2018). It is built on top of scikit-learn (Pedregosa et al., 2011).
  doc_url: https://docs.doubleml.org/stable/
  dev_url: https://github.com/DoubleML/doubleml-for-py

extra:
  recipe-maintainers:
    - SvenKlaassen
    - PhilippBach
    - MalteKurz
